// Generated by CoffeeScript 1.5.0
(function() {

  define(['aloha', 'aloha/plugin', 'jquery', 'aloha/ephemera', 'ui/ui', 'ui/button', 'semanticblock/semanticblock-plugin', 'css!embed/css/embed-plugin.css'], function(Aloha, Plugin, jQuery, Ephemera, UI, Button, semanticBlock) {
    var EMPTY, TEMPLATE;
    TEMPLATE = '<div class="embedded"></div>';
    EMPTY = '<div class="empty-state"><a href="">add a thing</a></div>';
    return Plugin.create('embed', {
      getLabel: function() {
        return 'Embeded';
      },
      selector: '.embedded',
      activate: function($element) {
        if (!$element.contents().length) {
          $element.append(jQuery(EMPTY));
        }
        return $element.on('click', '.empty-state a', function() {
          var embedCode;
          embedCode = prompt('code please');
          return $element.empty().append(embedCode);
        });
      },
      deactivate: function($element) {
        return $element.siblings('.empty-state').remove();
      },
      init: function() {
        return semanticBlock.register(this);
      }
    });
  });

}).call(this);
