// Generated by CoffeeScript 1.7.1
(function() {
  define(['aloha', 'jquery', 'aloha/plugin', 'ui/ui', 'ui/button', 'css!workarea/css/workarea.css'], function(Aloha, $, Plugin, Ui, Button) {
    var GENTICS;
    GENTICS = window.GENTICS;
    return Plugin.create('workarea', {
      init: function() {
        return this._button = Ui.adopt('insertWorkArea', Button, {
          tooltip: 'Insert Work Area',
          icon: 'aloha-icon-workarea',
          scope: 'Aloha.continuoustext',
          click: function() {
            var el, range;
            range = Aloha.Selection.getRangeObject();
            if (Aloha.activeEditable) {
              el = $('<div class="workarea">');
              GENTICS.Utils.Dom.insertIntoDOM(el, range, $(Aloha.activeEditable.obj), true);
              return range.select();
            }
          }
        });
      }
    });
  });

}).call(this);
