// Generated by CoffeeScript 1.7.1
(function() {
  define(['jquery', 'aloha', 'aloha/plugin', 'aloha/contenthandlermanager'], function($, Aloha, Plugin, ContentHandlerManager) {
    var makeCleaner;
    makeCleaner = function(WordHandler, settings) {
      return ContentHandlerManager.createHandler({
        handleContent: function(content) {
          var $content, xml, xmldoc;
          content = WordHandler.handleContent(content);
          $content = $("<div>" + content + "</div>");
          $content.find('*[class*="Mso"]').each(function(idx, el) {
            var c, remove, _i, _len, _ref;
            remove = "";
            _ref = el.classList;
            for (_i = 0, _len = _ref.length; _i < _len; _i++) {
              c = _ref[_i];
              if (/^Mso/.test(c)) {
                remove = "" + remove + " " + c;
              }
            }
            remove = remove.trim();
            if (remove) {
              return $(el).removeClass(remove);
            }
          });
          $content.find('*[style]').each(function(idx, el) {
            return $(el).removeAttr('style');
          });
          $content.find('a[href^="#"]').contents().unwrap();
          $content.find('h1,h2,h3,h4,h5,h6').each(function(idx, el) {
            var head, newhead;
            head = $(el).text();
            newhead = head.replace(/^[\d.]+([^ \s\d.])/, '$1');
            if (head !== newhead) {
              return $(el).text(newhead);
            }
          });
          if (settings.extra) {
            settings.extra($content);
          }
          xmldoc = document.implementation.createDocument('http://www.w3.org/1999/xhtml', 'body', null);
          $content.contents().clone().each(function(idx, node) {
            return xmldoc.documentElement.appendChild(node);
          });
          xml = (new XMLSerializer()).serializeToString(xmldoc);
          xml = xml.replace(/<\/body>$/, '').replace(/^<body[^>]*>/, '');
          return xml;
        }
      });
    };
    return Plugin.create('cleanup', {
      init: function() {
        return Aloha.require(['contenthandler/wordcontenthandler'], (function(_this) {
          return function(WordHandler) {
            return ContentHandlerManager.register('cleanup', makeCleaner(WordHandler, _this.settings));
          };
        })(this));
      }
    });
  });

}).call(this);
